import "./globals.css";
import Navbar from "../components/Navbar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="z-10">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
